# See: https://dart.dev/tools/pub/pubspec
name: model_viewer
version: 1.0.0
description: >-
  A Flutter widget for rendering interactive 3D models in the glTF and GLB
  formats.
homepage: https://github.com/drydart/model_viewer.dart
repository: https://github.com/drydart/model_viewer.dart
issue_tracker: https://github.com/drydart/model_viewer.dart/issues
dependencies:
  flutter:
    sdk: flutter
  android_intent_plus: ^3.0.2
  webview_flutter: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
environment:
  sdk: '>=2.12.0 <3.0.0'
flutter:
  assets:
    - etc/assets/template.html
    - etc/assets/model-viewer.js
